---

kind: pipeline
type: docker
name: main

platform:
  os: linux
  arch: amd64

steps:

  - name: test
    image: iwilltry42/k3d-ci:v4.0.0-alpha.1
    commands:
      - sleep 20
      - k3d version
    volumes:
      - name: k3dconf
        path: /tmp/k3d

services:
  - name: k3d
    image: iwilltry42/k3d:v4.0.0-alpha.1-dind
    privileged: true
    commands:
      - dockerd-entrypoint.sh &
      - sleep 4
      - ps aux
      - until docker ps 2>&1 > /dev/null; do echo "waiting for docker to start..." && sleep 1; done
      - k3d cluster create
    volumes:
      - name: k3dconf
        path: /tmp/k3d

volumes:
  - name: k3dconf
    temp: {}