---

kind: pipeline
type: docker
name: main

platform:
  os: linux
  arch: amd64

steps:

  - name: test
    image: iwilltry42/k3d-ci:v4.0.0-alpha.1
    commands:
      - until docker ps 2>&1 > /dev/null; do echo "waiting for docker to start..." && sleep 1; done
      - mkdir -p ~/.kube/config
      - k3d version
      - k3d cluster create
      - k3d cluster list
      - sleep 5
      - netstat -ntlp
    volumes:
      - name: dockersock
        path: /var/run

services:
  # Starting the docker service to be used by dind
  - name: docker
    image: docker:19.03-dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}